config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :warzones

  resources :killteams do
    resources :batreps, only: [:new, :create]
  end

  # resources :batreps, only: [:show, :edit, :update, :destroy]


  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batrep.rb
class Batrep < ApplicationRecord
  belongs_to :killteam
  has_one :warzone
end

app/models/killteam.rb
class Killteam < ApplicationRecord
  belongs_to :user
  has_many :batreps, dependent: :destroy
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :killteams
end

app/models/warzone.rb
class Warzone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/batreps_controller.rb
class BatrepsController < ApplicationController

  before_action :set_killteam, only: %[new create]

  def new
    @killteam = Killteam.find(params[:killteam_id])
    @batrep = Batrep.new(killteam_id: @killteam.id)
  end

  def create
    @batrep = Batrep.new(batrep_params)
    @batrep.killteam = @killteam
    @batrep.save
    redirect_to killteam_path(@killteam)
  end

  private

  def set_killteam
    @killteam = Killteam.find(params[:killteam_id])
  end

  def batrep_params
    params.require(:batrep).permit(:title, :report, :versus)
  end
end

app/controllers/killteams_controller.rb
class KillteamsController < ApplicationController
  before_action :set_killteam, only: %i[ show edit update destroy ]

  # GET /killteams or /killteams.json
  def index
    @killteams = Killteam.all
  end

  # GET /killteams/1 or /killteams/1.json
  def show
    @killteam = Killteam.find(params[:id])
    # authorize @killteam
    # @killteam.user = current_user
  end

  # GET /killteams/new
  def new
    @killteam = Killteam.new
  end

  # GET /killteams/1/edit
  def edit
    @killteam = Killteam.find(params[:id])
  end

  # POST /killteams or /killteams.json
  def create
    @killteam = Killteam.new(killteam_params)
    @killteam.user_id = current_user.id

    respond_to do |format|
      if @killteam.save
        format.html { redirect_to killteam_url(@killteam), notice: "Killteam was successfully created." }
        format.json { render :show, status: :created, location: @killteam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @killteam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /killteams/1 or /killteams/1.json
  def update
    respond_to do |format|
      if @killteam.update(killteam_params)
        format.html { redirect_to killteam_url(@killteam), notice: "Killteam was successfully updated." }
        format.json { render :show, status: :ok, location: @killteam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @killteam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /killteams/1 or /killteams/1.json
  def destroy
    @killteam.destroy

    respond_to do |format|
      format.html { redirect_to killteams_url, notice: "Killteam was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_killteam
      @killteam = Killteam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def killteam_params
      params.require(:killteam).permit(:name, :description, :requisition, :assetcap, :base, :factionkeyword, images: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/warzones_controller.rb
class WarzonesController < ApplicationController
  before_action :set_warzone, only: %i[ show edit update destroy ]

  # GET /warzones or /warzones.json
  def index
    @warzones = Warzone.all
  end

  # GET /warzones/1 or /warzones/1.json
  def show
  end

  # GET /warzones/new
  def new
    @warzone = Warzone.new
  end

  # GET /warzones/1/edit
  def edit
  end

  # POST /warzones or /warzones.json
  def create
    @warzone = Warzone.new(warzone_params)

    respond_to do |format|
      if @warzone.save
        format.html { redirect_to warzone_url(@warzone), notice: "Warzone was successfully created." }
        format.json { render :show, status: :created, location: @warzone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warzone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warzones/1 or /warzones/1.json
  def update
    respond_to do |format|
      if @warzone.update(warzone_params)
        format.html { redirect_to warzone_url(@warzone), notice: "Warzone was successfully updated." }
        format.json { render :show, status: :ok, location: @warzone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @warzone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warzones/1 or /warzones/1.json
  def destroy
    @warzone.destroy

    respond_to do |format|
      format.html { redirect_to warzones_url, notice: "Warzone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warzone
      @warzone = Warzone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warzone_params
      params.require(:warzone).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/batreps/_form.html.erb
<%= simple_form_for(@batrep) do |f| %>


  <div class="form-inputs">
    <%= f.input :title, label: 'Report title' %>
    <%= f.input :report %>


    <%# <%= f.input :killteam_id, label: 'Opposing team', as: :select, collection: [[Killteam.first.name, Killteam.first.id], [Killteam.last.name, Killteam.last.id]] %> %>



  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/batreps/index.html.erb
<h1 style="color: white;">Battle reports:</h1>

<table>
  <thead>
    <tr>
      <th style="color: white;">Name</th>
      <th style="color: white;">Team 1</th>
      <th style="color: white;">Team 2</th>

    </tr>
  </thead>

  <tbody>
    <% @batreps.each do |batrep| %>
      <tr>
        <td><%= batrep.title %></td>
        <td><%= batrep.killteam.name %></td>
        <td><%= batrep.user_id %></td>

        <%# <td><%= link_to 'Show', batrep </td> %>

        <%# <td><%= link_to 'Destroy', batrep, method: :delete, data: { confirm: 'Are you sure?' } %></td> %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/batreps/new.html.erb
<%# <div style="margin-left: 20px; color: white;">
  <h1 style="color: white;">Battle Report:</h1>

  <%= render 'form', batrep: @batrep %>

  <%# <%= link_to 'Back', killteams_path %>
<%# </div> %>

<h1>New batrep</h1>
<%= simple_form_for [@killteam, @batrep] do |f| %>
  <%= f.input :title %>
  <%= f.input :report %>
  <%= f.input :versus %>
  <%= f.submit "Submit report", class: "btn btn-primary" %>
<% end %>

app/views/batreps/show.html.erb
<h1>batrep</h1>


<p>
  <strong>Name:</strong>
  <%= @batrep.title %>
</p>

<p>
  <strong>Report:</strong>
  <%= @batrep.report %>
</p>

<p>
  <strong>Team 1:</strong>
  <%= @batrep.killteam.name %>
</p>

<p>
  <strong>Team 2:</strong>
  <%= @batrep.versus %>
</p>

<%# <%= link_to 'Edit', edit_killteam_path(@killteam) %> |
<%# <%= link_to 'Back', killteams_path %>

app/views/killteams/_form.html.erb
<%= simple_form_for(@killteam) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :requisition %>
    <%= f.input :assetcap %>
    <%= f.input :base %>
    <%= f.input :factionkeyword %>
    <%= f.input :images, as: :file, input_html: { multiple: true }%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/killteams/edit.html.erb
<h1>Editing Killteam</h1>

<%= render 'form', killteam: @killteam %>

<%= link_to 'Show', @killteam %> |
<%= link_to 'Back', killteams_path %>

app/views/killteams/index.html.erb
<p id="notice"><%= notice %></p>

<div style="padding-left: 20px; padding-bottom: 10px">
  <h1 style="color: white;">Killteams</h1>

  <%= link_to 'New Killteam', new_killteam_path %>
</div>

  <div class="grid">
    <% @killteams.each do |killteam| %>
      <div class="teamcard">
        <div class="infocontainer">
          <ul class="no-bullets">
            <li><h4><strong><%= killteam.name %></strong></h4></li>
            <li><%= killteam.description %></li>
            <br>
            <%# <li>Requisition Points: <%= killteam.requisition %></li>
            <%# <li>Asset Cap: <%= killteam.assetcap %></li>
            <li>Base: <%= killteam.base %></li>
            <li>Faction Keyword: <%= killteam.factionkeyword %></li>
            <br>
            <li><%= link_to 'Show', killteam %>
            <%# <% if killteam.user == current_user %>
              <%# <%= link_to 'Edit', edit_killteam_path(killteam) %>
              <%# <%= link_to 'Destroy', killteam, method: :delete, data: { confirm: 'Are you sure?' } %>

            <%# <%end%>
            </li>
          </ul>
        </div>

        <div class="imagecontainer" style="width:300px; height: auto;">
          <% if killteam.images.attached?%>
                <% killteam.images.each do |image| %>
                  <div class="ktimgframe">
                    <%= cl_image_tag image.key, height: 300, width: 400, crop: :fill%>
                  </div>
                <% end %>
            <% end %>
        </div>
      </div>
    <% end %>
  <div>

<br>

app/views/killteams/new.html.erb
<h1>New Killteam</h1>

<%= render 'form', killteam: @killteam %>

<%= link_to 'Back', killteams_path %>

app/views/killteams/show.html.erb
<p id="notice"><%= notice %></p>

<p style="color: white;">
  <strong>Name:</strong>
  <%= @killteam.name %>
</p>

<p style="color: white;">
  <strong>Description:</strong>
  <%= @killteam.description %>
</p>

<p style="color: white;">
  <strong>Requisition:</strong>
  <%= @killteam.requisition %>
</p>

<p style="color: white;">
  <strong>Assetcap:</strong>
  <%= @killteam.assetcap %>
</p>

<p style="color: white;">
  <strong>Base:</strong>
  <%= @killteam.base %>
</p>

<p style="color: white;">
  <strong>Faction Keyword:</strong>
  <%= @killteam.factionkeyword %>
</p>

<div class="grid">
  <% if @killteam.images.attached?%>
      <% @killteam.images.each do |image| %>
        <div class="ktframe" style='width:300px; height: 300px'>
          <%= cl_image_tag image.key, height: 300, width: 400, crop: :fill%>
        </div>
      <% end %>
  <% end %>
</div>

<div>
  <br>

  <% if @killteam.user == current_user %>
    <%=  %>
    <%= link_to 'Edit', edit_killteam_path(@killteam) %> |
    <%= link_to 'Back', killteams_path %>
    <%= link_to 'Log a new Battle report', new_killteam_batrep_path(:killteam_id) %>
  <% end %>

</div>
<%# <%= link_to 'Battle Reports', killteam_batreps(@killteam) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KtNarrative</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="" style="margin-left: 20px; color: white;">
  <br>
  <h1 >Welcome to the Kill Team Narrative tracker</h1>
  <p>Log your forces' progress and add to the campaign setting with personalized battle reports</p>

  <%= link_to "Killteams", killteams_url %>
  <%= link_to "Warzones", warzones_url %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="">
  <%= link_to "/", class: "navbar-brand" do %>
    <div class="skull-icon">
      <i class="fas fa-skull-crossbones"></i>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
                <li class="nav-item">
          <%= link_to "Killteams", killteams_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Warzones", warzones_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%# <%= link_to "Battle reports", batreps_path, class: "nav-link" %> %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/warzones/_form.html.erb
<%= simple_form_for(@warzone) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" style="color: white;">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions" style="color: white;">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/warzones/edit.html.erb
<h1>Editing Warzone</h1>

<%= render 'form', warzone: @warzone %>

<%= link_to 'Show', @warzone %> |
<%= link_to 'Back', warzones_path %>

app/views/warzones/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="color: white;">Warzones</h1>

<table style="color: white;">
  <thead>
    <tr style="color: white;">
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% planetSites = []  %>

  <tbody>
    <% @warzones.each do |warzone| %>
      <tr>
        <td><%= warzone.name %></td>
        <td><%= warzone.description %></td>
        <td><%= link_to 'Show', warzone %></td>
        <td><%= link_to 'Edit', edit_warzone_path(warzone) %></td>
        <td><%= link_to 'Destroy', warzone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% planetSites.push warzone %>
    <% end %>
  </tbody>
</table>


<div class="planet">
  <div class="wrap">
    <div class="background"></div>
    <div class="clouds"></div>
  </div>
  <div class="mask"></div>
  <div class="highlight highlight1" >
    <%= link_to planetSites[0].name, planetSites[0] %>
  </div>
  <div class="highlight highlight2" >
    <% if planetSites.length == 2 %>
    <%= link_to planetSites[1].name, planetSites[1]%>
    <% end %>
    <%# <%= else "" %>
  </div>
  <div class="highlight highlight3">
    <% if planetSites.length == 3 %>
    <%= link_to planetSites[2].name, planetSites[2]%>
    <% end %>

  </div>
</div>


<br>

<%= link_to 'New Warzone', new_warzone_path %>

app/views/warzones/new.html.erb
<h1 style="color: white;">New Warzone</h1>

<%= render 'form', warzone: @warzone %>

<%= link_to 'Back', warzones_path %>

app/views/warzones/show.html.erb
<p id="notice"><%= notice %></p>

<p style="color: white;">
  <strong>Name:</strong>
  <%= @warzone.name %>
</p>

<p style="color: white;">
  <strong>Description:</strong>
  <%= @warzone.description %>
</p>

<%= link_to 'Edit', edit_warzone_path(@warzone) %> |
<%= link_to 'Back', warzones_path %>